// Generated by https://quicktype.io

export interface ICliente {
    nif:       string;
    nombre:    string;
    apellidos: string;
    direccion: string;
    ciudad:    string;
    localidad: string;
}
